package com.carto.sn.enums;

public enum EnumPrivilege {
	AJOUTER_PROJET,
	MODIFIER_PROJET,
	SUPPRIMER_PROJET,
	AJOUTER_UTILISATEUR,
	MODIFIER_UTILISATEUR,
	SUPPRIMER_UTILISATEUR,
	AJOUTER_PROFIL,
	SUPPRIMER_PROFIL,
	AJOUTER_TYPE,
	MODIFIER_TYPE,
	SUPPRIMER_TYPE,
	AJOUTER_CATEGORIE,
	MODIFIER_CATEGORIE,
	SUPPRIMER_CATEGORIE;

}
